/*
 * Swagger Getting Started
 *
 * getting started
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"errors"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type ApiService struct {
}

// NewDefaultApiService creates a default api service
func NewApiService() DefaultApiServicer {
	return &ApiService{}
}

// AddUser -
func (s *ApiService) AddUser(newUser NewUser) (interface{}, error) {
	// TODO - update AddUser with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'AddUser' not implemented")
}

// DeleteUser -
func (s *ApiService) DeleteUser(id int64) (interface{}, error) {
	// TODO - update DeleteUser with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DeleteUser' not implemented")
}

// GetUser -
func (s *ApiService) GetUser(id int64) (interface{}, error) {
	// TODO - update GetUser with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetUser' not implemented")
}

// ListUsers -
func (s *ApiService) ListUsers(active string) (interface{}, error) {
	// TODO - update ListUsers with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	return []*User{
		{
			Name: "Tom",
		},
	}, nil
	// return nil, errors.New("service method 'ListUsers' not implemented")
}

// UpdateUser -
func (s *ApiService) UpdateUser(id int64, user User) (interface{}, error) {
	// TODO - update UpdateUser with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'UpdateUser' not implemented")
}
