/*
 * Swagger Getting Started
 *
 * getting started
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	server "github.com/yhidai/openapi-getting-started/server/go"
)

func main() {
	log.Printf("Server started")

	apiService := server.NewApiService()
	apiController := server.NewApiController(apiService)

	router := server.NewRouter(apiController)

	log.Fatal(http.ListenAndServe(":8081", router))
}
